# Generated by Django 5.0.4 on 2024-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="infa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and Time"
                    ),
                ),
            ],
        ),
    ]
