# Generated by Django 5.0.4 on 2024-04-25 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dom", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
