# Generated by Django 5.0.4 on 2024-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dom", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infa",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date and Time"),
        ),
    ]
