# Generated by Django 5.0.4 on 2024-04-29 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dom", "0005_privatemessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="group",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="invitee",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="inviter",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="privatemessage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="privatemessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="PrivateMessage",
        ),
    ]
