# Generated by Django 5.0.4 on 2024-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dom", "0007_codepublication_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codepublication",
            name="likes",
        ),
        migrations.AddField(
            model_name="codepublication",
            name="language",
            field=models.CharField(default="HTML", max_length=50),
        ),
        migrations.AlterField(
            model_name="codepublication",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
